name: test-tlm_adjoint-firedrake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    container:
      image: firedrakeproject/firedrake:latest
      options: --user root
    env:
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          path: 'tlm_adjoint'
      - name: Run tests
        run: |
          . /home/firedrake/firedrake/bin/activate
          cd tlm_adjoint
          pytest -v tests/firedrake
